
services:
  web:
    build: .
    container_name: receipt_scraper_project
    command: >
      sh -c "
      python manage.py migrate &&
      gunicorn receipt_scraper_project.wsgi:application --bind 0.0.0.0:8000 --workers 3 --threads 3 --timeout 3600 --log-level=debug"
    ports:
      - "8000:8000"
    # env_file:
    #   - .env
    # depends_on:
    #   - db
    #   - redis
    # networks:
    #   - app-network

#   db:
#     image: postgres:latest
#     container_name: postgres_db
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     env_file:
#       - .env
#     networks:
#       - app-network
#     ports:
#       - "5343:5432"

#   redis:
#     image: redis:latest
#     container_name: redis
#     ports:
#       - "6379:6379"
#     networks:
#       - app-network

#   celery_worker:
#     build: .
#     container_name: celery_worker
#     command: celery -A chuolink_backend worker --loglevel=info
#     env_file:
#       - .env
#     depends_on:
#       - redis
#       - web
#     networks:
#       - app-network

#   celery_beat:
#     build: .
#     container_name: celery_beat
#     command: celery -A chuolink_backend beat --loglevel=info
#     env_file:
#       - .env
#     depends_on:
#       - redis
#       - web
#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge
# volumes:
#   postgres_data:
#     driver: local




